### ISSUE TITLE
New release with current code?

### ISSUE THREAD

**Issue by Jakuje** [PL4typus/virt_cacard#12]
Hi Pierre,
Would it be possible to create a new release with the current code (the last one from last may is quite outdated) so I can simply create a RPM package out of that?

**Comment by PL4typus** [comment]
Hi Jakub, 

Sorry I didn't check GitHub in a while, I've been quite busy ! I will get to this ASAP

**Comment by Jakuje** [comment]
Thank you. The latest release look good. FYI, I created a copr repository with the needed packages to avoid rebuilding all the time, when we are testing, or if you would find some use for it:

https://copr.fedorainfracloud.org/coprs/jjelen/vsmartcard/
